[project]
name = ""
version = ""
description = ""
authors = [
    {name = "snorkysnark", email = "snorkysnark@gmail.com"},
]
dependencies = [
    "openpyxl>=3.1.2",
    "pandas==1.5.3",
]
requires-python = ">=3.10"
license = {text = "MIT"}
